
# To set any option to its default, just remove the option from the config file.
#
# Disenchant Cost = (EnchantmentLevel * LevelMultiplier) * (Offset - (EnchantmentRarity * RarityMultiplier))
#     All values must be in the range of 0.00 to 10.00, values outside of range will be set to default
[DisenchantCost]
	# If LevelMultiplier is set to 0.00, cost will always be 0"
	LevelMultiplier = 5.0
	RarityMultiplier = 0.03
	Offset = 1.6

